#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gnome-video-effects
Version  : 0.4.3
Release  : 2
URL      : https://download.gnome.org/sources/gnome-video-effects/0.4/gnome-video-effects-0.4.3.tar.xz
Source0  : https://download.gnome.org/sources/gnome-video-effects/0.4/gnome-video-effects-0.4.3.tar.xz
Summary  : A collection of GStreamer effects to be used in different GNOME Modules
Group    : Development/Tools
License  : GPL-2.0
Requires: gnome-video-effects-data
BuildRequires : gettext
BuildRequires : intltool
BuildRequires : perl(XML::Parser)

%description
Introduction
============
Writing effects is very easy: just create a file with the extion ".effect" and
use the following format for it:

%package data
Summary: data components for the gnome-video-effects package.
Group: Data

%description data
data components for the gnome-video-effects package.


%package dev
Summary: dev components for the gnome-video-effects package.
Group: Development
Requires: gnome-video-effects-data
Provides: gnome-video-effects-devel

%description dev
dev components for the gnome-video-effects package.


%prep
%setup -q -n gnome-video-effects-0.4.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1517949222
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1517949222
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/gnome-video-effects/bulge.effect
/usr/share/gnome-video-effects/cartoon.effect
/usr/share/gnome-video-effects/cheguevara.effect
/usr/share/gnome-video-effects/chrome.effect
/usr/share/gnome-video-effects/dicetv.effect
/usr/share/gnome-video-effects/distortion.effect
/usr/share/gnome-video-effects/edgetv.effect
/usr/share/gnome-video-effects/flip.effect
/usr/share/gnome-video-effects/heat.effect
/usr/share/gnome-video-effects/historical.effect
/usr/share/gnome-video-effects/hulk.effect
/usr/share/gnome-video-effects/inversion.effect
/usr/share/gnome-video-effects/kaleidoscope.effect
/usr/share/gnome-video-effects/mauve.effect
/usr/share/gnome-video-effects/mirror.effect
/usr/share/gnome-video-effects/noir.effect
/usr/share/gnome-video-effects/optv.effect
/usr/share/gnome-video-effects/pinch.effect
/usr/share/gnome-video-effects/quarktv.effect
/usr/share/gnome-video-effects/radioactv.effect
/usr/share/gnome-video-effects/revtv.effect
/usr/share/gnome-video-effects/ripple.effect
/usr/share/gnome-video-effects/saturation.effect
/usr/share/gnome-video-effects/sepia.effect
/usr/share/gnome-video-effects/shagadelictv.effect
/usr/share/gnome-video-effects/sobel.effect
/usr/share/gnome-video-effects/square.effect
/usr/share/gnome-video-effects/streaktv.effect
/usr/share/gnome-video-effects/stretch.effect
/usr/share/gnome-video-effects/timedelay.effect
/usr/share/gnome-video-effects/twirl.effect
/usr/share/gnome-video-effects/vertigotv.effect
/usr/share/gnome-video-effects/warptv.effect
/usr/share/gnome-video-effects/xray.effect

%files dev
%defattr(-,root,root,-)
/usr/lib64/pkgconfig/gnome-video-effects.pc
